service: library-app
frameworkVersion: '2'
configValidationMode: error

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:*"
    - Effect: Allow
      Action:
        - "cloudwatch:*"
      Resource: "arn:aws:logs:*:*:*"
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - "*"
      allowedMethods:
        - '*'
package:
  patterns:
    - "!**"
    - 'bin/lambda'
functions:
  hello:
    handler: bin/lambda
    events:
      - httpApi:
          path: '*'
          method: '*'
resources:
  Resources:
    ApiDoc:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        AttributeDefinitions:
          - AttributeName: 'Isbn' # time ordered uuid
            AttributeType: S
        KeySchema:
          - AttributeName: 'Isbn'
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ExampleLibraryApp